---
- name: Linux
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: transfer_options
      prompt: |
        [TRANSFER] Do you want to transfer image?
        0: Thansfer Image
        1: other
      private: false
      default: 1

  vars:
    transfer_choice:
      '0': 'transfer'
      '1': 'other'
    desktop_choice:
      '0': 'no desktop'
      '1': 'xfce'
    webgui_choice:
      '0': 'no web GUI'
      '1': 'cockpit'

  pre_tasks:
    - set_fact:
        transfer: "{{ transfer_choice[transfer_options] | default(transfer_choice['0']) }}"

    - block:
        - pause:
            prompt: |
              [DESKTOP] What desktop do you want to install?
              0: Don't install any GUI
              1: xfce

              Default is 0
          register: desktop_options

        - pause:
            prompt: |
              [WEBGUI] What web GUI do you want to install?
              0: Don't install any web GUI.
              1: cockpit

              Default is 0
          register: webgui_options

        - debug:
            msg: "Your inputs are {{ transfer_options }}, {{ desktop_input }}, {{ webgui_input }}"
          vars:
            desktop_input: "{{ (desktop_options.user_input is truthy) | ternary(desktop_options.user_input, '0') }}"
            webgui_input: "{{ (webgui_options.user_input is truthy) | ternary(webgui_options.user_input, '0') }}"

        - set_fact:
            desktop: "{{ desktop_choice[desktop_options.user_input] | default(desktop_choice['0']) }}"
            webgui: "{{ webgui_choice[webgui_options.user_input] | default(webgui_choice['0']) }}"

      when: transfer_options == '1'
      
    
    os_desktop: "{{linux_desktop_select[linux_desktop_selection]}}"
    common_install_tools: 
      - "{{linux_webgui_select[linux_webgui_selection]}}"

  roles:
   - { role: role_common, tags: "role_common"} 
   - { role: role_cloud, tags: "role_cloud"} 
   - { role: role_os, tags: "role_os"}
   - { role: role_preend, tags: "role_preend"} 
   - { role: role_end, tags: "role_end"}
