---
- name: Linux
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'linux_desktop_selection'
      prompt: "\nChoose the Desktop you want to install [ 1/2/3/4] \n\n
      0: Don't install any GUI\n
      1: GNOME \n
      2: KDE \n
      3: Xfce\n
      4: Mate\n"
      private: no
      default: 1
      
    - name: 'linux_webgui_selection'
      prompt: "\nChoose the Web GUI you want to install [ 1/2/3/4] \n\n
      0: Don't install any Web GUI\n
      1: cockpit \n"
      private: no
      default: 0

  vars:
    linux_desktop_select:
      '0': ''
      '1': 'gnome'
      '2': 'kde'
      '3': 'xfce'
      '4': 'mate'
      
    linux_webgui_select:
      '0': ''
      '1': 'cockpit'
      
    os_desktop: "{{linux_desktop_select[linux_desktop_selection]}}"
    common_install_tools: 
      - "{{linux_webgui_select[linux_webgui_selection]}}"

  roles:
   - { role: role_common, tags: "role_common"} 
   - { role: role_cloud, tags: "role_cloud"} 
   - { role: role_os, tags: "role_os"}
   - { role: role_preend, tags: "role_preend"} 
   - { role: role_end, tags: "role_end"}
