- src: http://github.com/websoft9dev/role_common

- src: http://github.com/websoft9dev/role_cloud

- src: http://github.com/websoft9dev/role_os

- src: http://github.com/websoft9dev/role_preend

- src: http://github.com/websoft9dev/role_end
