- src: http://github.com/websoft9dev/role_common
  version: master

- src: http://github.com/websoft9dev/role_cloud
  version: master

- src: http://github.com/websoft9dev/role_os
  version: master

- src: http://github.com/websoft9dev/role_preend
  version: master

- src: http://github.com/websoft9dev/role_end
  version: master